### ISSUE TITLE
Adding ServerVariables and QueryString to Log.

### ISSUE THREAD

**Issue by rstone770** [elmahio/Elmah.Io.Extensions.Logging#2]
Hey i noticed then when populating CreateMessage from log state, you don't attempt to populate ServerVariables or QueryString. 

[Here](https://github.com/elmahio/Elmah.Io.Extensions.Logging/blob/master/src/Elmah.Io.Extensions.Logging/ElmahIoLogger.cs#L68) is the link to the source for reference.

Can we please add support for this?

**Comment by ThomasArdal** [comment]
The problem is that Microsoft.Extensions.Logging isn't HTTP aware. It can be used from any .NET project, like a console app that wouldn't have server variables or a query string. In the old days (with ASP.NET), you could just reference `System.Web` and try to make a call to `HttpContext.Current`. But I don't feel that I can justify making the package dependent of any web packages, when Microsoft.Extensions.Logging isn't.

Makes sense? You could decorate all log messages with these info, using the `OnMessage` event as shown here: https://docs.elmah.io/logging-to-elmah-io-from-microsoft-extensions-logging/#decorating-log-messages

**Comment by rstone770** [comment]
Hey Thomas, thanks for getting back.

I actually meant pulling those values out of state like all the other
values, not HttpContext.



On Jan 12, 2019 1:39 AM, "Thomas Ardal" <notifications@github.com> wrote:

The problem is that Microsoft.Extensions.Logging isn't HTTP aware. It can
be used from any .NET project, like a console app that wouldn't have server
variables or a query string. In the old days (with ASP.NET), you could just
reference System.Web and try to make a call to HttpContext.Current. But I
don't feel that I can justify making the package dependent of any web
packages, when Microsoft.Extensions.Logging isn't.

Makes sense? You could decorate all log messages with these info, using the
OnMessage event as shown here:
https://docs.elmah.io/logging-to-elmah-io-from-microsoft-extensions-logging/#decorating-log-messages

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/elmahio/Elmah.Io.Extensions.Logging/issues/2#issuecomment-453730716>,
or mute the thread

**Comment by ThomasArdal** [comment]
Ahh. So doing something like this would set server variables:

```csharp
log.Information("this is {serverVariables}", new[] { new { key = "Key", value = "Value" } });
```

?

**Comment by rstone770** [comment]
I would ideally like ServerVariables sent as the ServerVariables property of Message and not just interpolated text. Adding ServerVariables would add those fields to the proper tab in elmah.io which would also honor special interesting fields like User-Agent. Right now it just gets appended to Data which isnt as useful. 

I was trying to create a gist of my actual use case but for some reason i cant log into visual studios to retrieve code, i think they are having transient outages right now.

**Comment by ThomasArdal** [comment]
Yup. That was the intent with my code samples as well. Better sample:

```csharp
log.Information("this is {serverVariables}", new[] { new { key = "User-Agent", value = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36" } });
```

would but a User-Agent beneath the Server Variables tab on the error details on elmah.io.

That's a good idea for sure and something I thought about when I created support for setting other elmah.io fields using variables a couple of months ago. I didn't support lists at the time, since I couldn't decide on what the user should provide as the `serverVariables` object for this to work. But a simple implementation could be "put this in Server Variables if the property key matches `serverVariables` and the object is of type dictionary".

**Comment by rstone770** [comment]
I like this. If you assume that server variables are of type KeyValue you
could reuse some of your existing item project code too. After it could be
extended to other collections like query string.

I can write this and submit if a pr if you would like.

**Comment by ThomasArdal** [comment]
A PR would be awesome. Think you are right about anything being a collection of KeyValue should go in there.

**Comment by rstone770** [comment]
I added a PR for just the ServerVariables. #3

**Comment by rstone770** [comment]
Hey @ThomasArdal. I've been testing those pre release changes we made over the last couple weeks, and it seems to be working as we'd expect. 

Just for context, ive been running this through ILogger via asp in a .netcore 2.1 environment.

**Comment by ThomasArdal** [comment]
Hey @rstone770. Sounds great. We are also running with the new prerelease in production now, and everything seems to work great. Will release a stable version asap. Thank you for your help testing this 👍

**Comment by ThomasArdal** [comment]
https://www.nuget.org/packages/Elmah.Io.Extensions.Logging/3.4.38
